# Generated by Django 3.2.16 on 2024-09-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bithday',
            new_name='Birthday',
        ),
    ]
