# Generated by Django 3.2.16 on 2024-10-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_auto_20241010_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
